# Generated by Django 3.0.1 on 2019-12-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa Produktu')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Odnośnik')),
                ('icon', models.ImageField(upload_to='icons', verbose_name='Ikona Produktu')),
                ('number', models.IntegerField(verbose_name='Liczba Sztuk')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=15, verbose_name='Imie')),
                ('surname', models.TextField(verbose_name='Nazwisko')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Odnośnik')),
                ('products', models.ManyToManyField(to='products.Product', verbose_name='Produkty')),
            ],
        ),
    ]
