# Generated by Django 3.0.1 on 2019-12-28 23:51

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191228_1735'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('category', django.db.models.manager.Manager()),
            ],
        ),
    ]
