# Generated by Django 3.0.1 on 2019-12-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191229_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.ImageField(upload_to='products/static/images', verbose_name='Ikona Produktu'),
        ),
    ]
