# Generated by Django 3.0.1 on 2020-01-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icon1',
            field=models.ImageField(default=False, upload_to='products/%Y/%m/%d', verbose_name='Zdjecie 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='icon2',
            field=models.ImageField(default=False, upload_to='products/%Y/%m/%d', verbose_name='Zdjecie 2'),
        ),
    ]
