# Generated by Django 3.0.1 on 2020-01-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200105_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_data',
            field=models.DateTimeField(),
        ),
    ]
