# Generated by Django 3.0.1 on 2020-01-07 01:09

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200105_2306'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderproduct',
            managers=[
                ('orderproduct', django.db.models.manager.Manager()),
            ],
        ),
    ]
