# Generated by Django 3.0.1 on 2020-01-07 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200107_0209'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderproduct',
            managers=[
            ],
        ),
    ]
