# Generated by Django 3.0.1 on 2020-01-10 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_orderadress'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderadress',
            managers=[
            ],
        ),
    ]
