# Generated by Django 3.0.1 on 2020-01-10 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20200110_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderadress',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Order'),
        ),
    ]
