# Generated by Django 3.0.1 on 2020-01-11 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20200110_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderadress',
            name='order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.Order'),
        ),
    ]
